java -Xmx4G -jar pXg.v2.2.1.jar \
    --gtf_file toy_datasets/toy.gtf \
    --sam_file toy_datasets/toy.sorted.sam \
    --psm_file toy_datasets/toy.psm.csv \
    --fasta_file toy_datasets/toy.fasta \
    --output toy \
    --file_col 2 \
    --pept_col 4 \
    --scan_col 5 \
    --score_col 8 \
    --charge_col 11 \
    --add_feat_cols 15 \
    --sep csv \
    --mode 3 \
    --threads 2
